#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ajito_ch0200

#include "Basic.hpp"

#include "BP_Ajito_ch0200_classes.hpp"
#include "BP_Ajito_ch0200_parameters.hpp"


namespace SDK
{

// Function BP_Ajito_ch0200.BP_Ajito_ch0200_C.SetWoodDamageParam
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Param                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ajito_ch0200_C::SetWoodDamageParam(float Param)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ajito_ch0200_C", "SetWoodDamageParam");

	Params::BP_Ajito_ch0200_C_SetWoodDamageParam Parms{};

	Parms.Param = Param;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ajito_ch0200.BP_Ajito_ch0200_C.WaterMove
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    On                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Ajito_ch0200_C::WaterMove(bool On)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ajito_ch0200_C", "WaterMove");

	Params::BP_Ajito_ch0200_C_WaterMove Parms{};

	Parms.On = On;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ajito_ch0200.BP_Ajito_ch0200_C.WaterBreak
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ajito_ch0200_C::WaterBreak()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ajito_ch0200_C", "WaterBreak");

	UObject::ProcessEvent(Func, nullptr);
}

}

