#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BT_f06_200

#include "Basic.hpp"

#include "BP_BT_f06_200_classes.hpp"
#include "BP_BT_f06_200_parameters.hpp"


namespace SDK
{

// Function BP_BT_f06_200.BP_BT_f06_200_C.ExecuteUbergraph_BP_BT_f06_200
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BT_f06_200_C::ExecuteUbergraph_BP_BT_f06_200(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BT_f06_200_C", "ExecuteUbergraph_BP_BT_f06_200");

	Params::BP_BT_f06_200_C_ExecuteUbergraph_BP_BT_f06_200 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BT_f06_200.BP_BT_f06_200_C.StartEvent
// (Event, Public, BlueprintEvent)

void ABP_BT_f06_200_C::StartEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BT_f06_200_C", "StartEvent");

	UObject::ProcessEvent(Func, nullptr);
}

}

