#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_RSAtomComponent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EnvComponent.BP_EnvComponent_C
// 0x0010 (0x1270 - 0x1260)
class UBP_EnvComponent_C final : public UBP_RSAtomComponent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_EnvComponent_C;                  // 0x1260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_EnvComponent(int32 EntryPoint);
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void OnAcceleratorEnd(const struct FAcceleratorParam& Parameter, class AActor* Owner, float RemainTime, bool bHologram);
	void OnAcceleratorStart(const struct FAcceleratorParam& Parameter, class AActor* Owner, bool bHologram);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EnvComponent_C">();
	}
	static class UBP_EnvComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EnvComponent_C>();
	}
};
static_assert(alignof(UBP_EnvComponent_C) == 0x000010, "Wrong alignment on UBP_EnvComponent_C");
static_assert(sizeof(UBP_EnvComponent_C) == 0x001270, "Wrong size on UBP_EnvComponent_C");
static_assert(offsetof(UBP_EnvComponent_C, UberGraphFrame_BP_EnvComponent_C) == 0x001260, "Member 'UBP_EnvComponent_C::UberGraphFrame_BP_EnvComponent_C' has a wrong offset!");

}

