#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnemySpawnComponent

#include "Basic.hpp"

#include "BP_EnemySpawnComponent_classes.hpp"
#include "BP_EnemySpawnComponent_parameters.hpp"


namespace SDK
{

// Function BP_EnemySpawnComponent.BP_EnemySpawnComponent_C.StartSpawnEffect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsStartEffect                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FVector                          Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRotator                         Rotation                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_EnemySpawnComponent_C::StartSpawnEffect(bool IsStartEffect, const struct FVector& Location, const struct FRotator& Rotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnemySpawnComponent_C", "StartSpawnEffect");

	Params::BP_EnemySpawnComponent_C_StartSpawnEffect Parms{};

	Parms.IsStartEffect = IsStartEffect;
	Parms.Location = std::move(Location);
	Parms.Rotation = std::move(Rotation);

	UObject::ProcessEvent(Func, &Parms);
}

}

