#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EventMeshOption

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_EventMeshOption.BP_EventMeshOption_C.ExecuteUbergraph_BP_EventMeshOption
// 0x0008 (0x0008 - 0x0000)
struct BP_EventMeshOption_C_ExecuteUbergraph_BP_EventMeshOption final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EventMeshOption_C_ExecuteUbergraph_BP_EventMeshOption) == 0x000004, "Wrong alignment on BP_EventMeshOption_C_ExecuteUbergraph_BP_EventMeshOption");
static_assert(sizeof(BP_EventMeshOption_C_ExecuteUbergraph_BP_EventMeshOption) == 0x000008, "Wrong size on BP_EventMeshOption_C_ExecuteUbergraph_BP_EventMeshOption");
static_assert(offsetof(BP_EventMeshOption_C_ExecuteUbergraph_BP_EventMeshOption, EntryPoint) == 0x000000, "Member 'BP_EventMeshOption_C_ExecuteUbergraph_BP_EventMeshOption::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_ExecuteUbergraph_BP_EventMeshOption, K2Node_Event_EndPlayReason) == 0x000004, "Member 'BP_EventMeshOption_C_ExecuteUbergraph_BP_EventMeshOption::K2Node_Event_EndPlayReason' has a wrong offset!");

// Function BP_EventMeshOption.BP_EventMeshOption_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct BP_EventMeshOption_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EventMeshOption_C_ReceiveEndPlay) == 0x000001, "Wrong alignment on BP_EventMeshOption_C_ReceiveEndPlay");
static_assert(sizeof(BP_EventMeshOption_C_ReceiveEndPlay) == 0x000001, "Wrong size on BP_EventMeshOption_C_ReceiveEndPlay");
static_assert(offsetof(BP_EventMeshOption_C_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'BP_EventMeshOption_C_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

// Function BP_EventMeshOption.BP_EventMeshOption_C.Setup
// 0x00F8 (0x00F8 - 0x0000)
struct BP_EventMeshOption_C_Setup final
{
public:
	class UPrimitiveComponent*                    Primitive;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMeshCom;                                   // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ARSBattlePlayer_C*                      RSBattlePlayer;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URSAjitoAnimInstance*                   AjitoAnimInstLocal;                                // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URSNpcAnimInstance*                     NpcAnimInstLocal;                                  // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URSPlayerAnimInstance*                  AnimInstLocal;                                     // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalLocal;                                     // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B6A[0x3];                                     // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetPrimitiveBoundsScale_ReturnValue;      // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B6B[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_PlayerInterface_C> K2Node_DynamicCast_AsBPI_Player_Interface;         // 0x0048(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B6C[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_PlayerInterface_C> CallFunc_GetEnableRigidBody_self_CastInput;        // 0x0060(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetEnableRigidBody_enable;                // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B6D[0x7];                                     // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B6E[0x7];                                     // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSNpcAnimInstance*                     K2Node_DynamicCast_AsRSNpc_Anim_Instance;          // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B6F[0x7];                                     // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSPlayerAnimInstance*                  K2Node_DynamicCast_AsRSPlayer_Anim_Instance;       // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B70[0x6];                                     // 0x00A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_1;            // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ECollisionEnabled                             CallFunc_GetCollisionEnabled_ReturnValue;          // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBodySimulatingPhysics_ReturnValue;      // 0x00B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B71[0x5];                                     // 0x00B3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class URSAjitoAnimInstance*                   K2Node_DynamicCast_AsRSAjito_Anim_Instance;        // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B72[0x7];                                     // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSNpcAnimInstance*                     K2Node_DynamicCast_AsRSNpc_Anim_Instance_1;        // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B73[0x7];                                     // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSPlayerAnimInstance*                  K2Node_DynamicCast_AsRSPlayer_Anim_Instance_1;     // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EnableRigidBody_bDummy;                   // 0x00E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B74[0x5];                                     // 0x00E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 K2Node_DynamicCast_AsSkeletal_Mesh_Component;      // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_EventMeshOption_C_Setup) == 0x000008, "Wrong alignment on BP_EventMeshOption_C_Setup");
static_assert(sizeof(BP_EventMeshOption_C_Setup) == 0x0000F8, "Wrong size on BP_EventMeshOption_C_Setup");
static_assert(offsetof(BP_EventMeshOption_C_Setup, Primitive) == 0x000000, "Member 'BP_EventMeshOption_C_Setup::Primitive' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, SkeletalMeshCom) == 0x000008, "Member 'BP_EventMeshOption_C_Setup::SkeletalMeshCom' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, RSBattlePlayer) == 0x000010, "Member 'BP_EventMeshOption_C_Setup::RSBattlePlayer' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, AjitoAnimInstLocal) == 0x000018, "Member 'BP_EventMeshOption_C_Setup::AjitoAnimInstLocal' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, NpcAnimInstLocal) == 0x000020, "Member 'BP_EventMeshOption_C_Setup::NpcAnimInstLocal' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, AnimInstLocal) == 0x000028, "Member 'BP_EventMeshOption_C_Setup::AnimInstLocal' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, SkeletalLocal) == 0x000030, "Member 'BP_EventMeshOption_C_Setup::SkeletalLocal' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000038, "Member 'BP_EventMeshOption_C_Setup::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_GetPrimitiveBoundsScale_ReturnValue) == 0x00003C, "Member 'BP_EventMeshOption_C_Setup::CallFunc_GetPrimitiveBoundsScale_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_IsValid_ReturnValue) == 0x000040, "Member 'BP_EventMeshOption_C_Setup::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_AsBPI_Player_Interface) == 0x000048, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_AsBPI_Player_Interface' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_bSuccess) == 0x000058, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_GetEnableRigidBody_self_CastInput) == 0x000060, "Member 'BP_EventMeshOption_C_Setup::CallFunc_GetEnableRigidBody_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_GetEnableRigidBody_enable) == 0x000070, "Member 'BP_EventMeshOption_C_Setup::CallFunc_GetEnableRigidBody_enable' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_GetAnimInstance_ReturnValue) == 0x000078, "Member 'BP_EventMeshOption_C_Setup::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_IsValid_ReturnValue_1) == 0x000080, "Member 'BP_EventMeshOption_C_Setup::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_AsRSNpc_Anim_Instance) == 0x000088, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_AsRSNpc_Anim_Instance' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_bSuccess_1) == 0x000090, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_AsRSPlayer_Anim_Instance) == 0x000098, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_AsRSPlayer_Anim_Instance' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_bSuccess_2) == 0x0000A0, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_IsValid_ReturnValue_2) == 0x0000A1, "Member 'BP_EventMeshOption_C_Setup::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_GetAnimInstance_ReturnValue_1) == 0x0000A8, "Member 'BP_EventMeshOption_C_Setup::CallFunc_GetAnimInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_IsValid_ReturnValue_3) == 0x0000B0, "Member 'BP_EventMeshOption_C_Setup::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_GetCollisionEnabled_ReturnValue) == 0x0000B1, "Member 'BP_EventMeshOption_C_Setup::CallFunc_GetCollisionEnabled_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_IsBodySimulatingPhysics_ReturnValue) == 0x0000B2, "Member 'BP_EventMeshOption_C_Setup::CallFunc_IsBodySimulatingPhysics_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_AsRSAjito_Anim_Instance) == 0x0000B8, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_AsRSAjito_Anim_Instance' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_bSuccess_3) == 0x0000C0, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_AsRSNpc_Anim_Instance_1) == 0x0000C8, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_AsRSNpc_Anim_Instance_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_bSuccess_4) == 0x0000D0, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_AsRSPlayer_Anim_Instance_1) == 0x0000D8, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_AsRSPlayer_Anim_Instance_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_bSuccess_5) == 0x0000E0, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_IsValid_ReturnValue_4) == 0x0000E1, "Member 'BP_EventMeshOption_C_Setup::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, CallFunc_EnableRigidBody_bDummy) == 0x0000E2, "Member 'BP_EventMeshOption_C_Setup::CallFunc_EnableRigidBody_bDummy' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_AsSkeletal_Mesh_Component) == 0x0000E8, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_AsSkeletal_Mesh_Component' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Setup, K2Node_DynamicCast_bSuccess_6) == 0x0000F0, "Member 'BP_EventMeshOption_C_Setup::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");

// Function BP_EventMeshOption.BP_EventMeshOption_C.Initialize
// 0x00D0 (0x00D0 - 0x0000)
struct BP_EventMeshOption_C_Initialize final
{
public:
	bool                                          CallFunc_IsEditor_ReturnValue;                     // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B75[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetObjectName_ReturnValue;                // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0018(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0030(0x0040)(HasGetValueTypeHash)
	class ARSBattlePlayer_C*                      CallFunc_GetEventAttachedMesh_Player;              // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_MenuPlayerBase_C*                   CallFunc_GetEventAttachedMesh_MenuPlayer;          // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 CallFunc_GetEventAttachedMesh_SkeletalMeshComp;    // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_GetEventAttachedMesh_PrimitiveComp;       // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0090(0x0010)(ReferenceParm, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B76[0x7];                                     // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00A8(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EventMeshOption_C_Initialize) == 0x000008, "Wrong alignment on BP_EventMeshOption_C_Initialize");
static_assert(sizeof(BP_EventMeshOption_C_Initialize) == 0x0000D0, "Wrong size on BP_EventMeshOption_C_Initialize");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_IsEditor_ReturnValue) == 0x000000, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_IsEditor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_GetObjectName_ReturnValue) == 0x000008, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_GetObjectName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_Conv_StringToText_ReturnValue) == 0x000018, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, K2Node_MakeStruct_FormatArgumentData) == 0x000030, "Member 'BP_EventMeshOption_C_Initialize::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_GetEventAttachedMesh_Player) == 0x000070, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_GetEventAttachedMesh_Player' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_GetEventAttachedMesh_MenuPlayer) == 0x000078, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_GetEventAttachedMesh_MenuPlayer' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_GetEventAttachedMesh_SkeletalMeshComp) == 0x000080, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_GetEventAttachedMesh_SkeletalMeshComp' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_GetEventAttachedMesh_PrimitiveComp) == 0x000088, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_GetEventAttachedMesh_PrimitiveComp' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, K2Node_MakeArray_Array) == 0x000090, "Member 'BP_EventMeshOption_C_Initialize::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_IsValid_ReturnValue) == 0x0000A0, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_Format_ReturnValue) == 0x0000A8, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Initialize, CallFunc_Conv_TextToString_ReturnValue) == 0x0000C0, "Member 'BP_EventMeshOption_C_Initialize::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");

// Function BP_EventMeshOption.BP_EventMeshOption_C.Finalize
// 0x00C8 (0x00C8 - 0x0000)
struct BP_EventMeshOption_C_Finalize final
{
public:
	class URSAjitoAnimInstance*                   AjitoAnimInstLocal;                                // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URSNpcAnimInstance*                     NpcAnimInstLocal;                                  // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalLocal;                                     // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URSPlayerAnimInstance*                  AnimInstLocal;                                     // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B77[0x7];                                     // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSAjitoAnimInstance*                   K2Node_DynamicCast_AsRSAjito_Anim_Instance;        // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B78[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSNpcAnimInstance*                     K2Node_DynamicCast_AsRSNpc_Anim_Instance;          // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B79[0x7];                                     // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSPlayerAnimInstance*                  K2Node_DynamicCast_AsRSPlayer_Anim_Instance;       // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B7A[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 K2Node_DynamicCast_AsSkeletal_Mesh_Component;      // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B7B[0x7];                                     // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_PlayerInterface_C> K2Node_DynamicCast_AsBPI_Player_Interface;         // 0x0070(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EnableRigidBody_bDummy;                   // 0x0082(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B7C[0x5];                                     // 0x0083(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_1;            // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B7D[0x7];                                     // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 K2Node_DynamicCast_AsSkeletal_Mesh_Component_1;    // 0x0098(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B7E[0x7];                                     // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSNpcAnimInstance*                     K2Node_DynamicCast_AsRSNpc_Anim_Instance_1;        // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5B7F[0x7];                                     // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URSPlayerAnimInstance*                  K2Node_DynamicCast_AsRSPlayer_Anim_Instance_1;     // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_EventMeshOption_C_Finalize) == 0x000008, "Wrong alignment on BP_EventMeshOption_C_Finalize");
static_assert(sizeof(BP_EventMeshOption_C_Finalize) == 0x0000C8, "Wrong size on BP_EventMeshOption_C_Finalize");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, AjitoAnimInstLocal) == 0x000000, "Member 'BP_EventMeshOption_C_Finalize::AjitoAnimInstLocal' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, NpcAnimInstLocal) == 0x000008, "Member 'BP_EventMeshOption_C_Finalize::NpcAnimInstLocal' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, SkeletalLocal) == 0x000010, "Member 'BP_EventMeshOption_C_Finalize::SkeletalLocal' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, AnimInstLocal) == 0x000018, "Member 'BP_EventMeshOption_C_Finalize::AnimInstLocal' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, CallFunc_GetAnimInstance_ReturnValue) == 0x000020, "Member 'BP_EventMeshOption_C_Finalize::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'BP_EventMeshOption_C_Finalize::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_AsRSAjito_Anim_Instance) == 0x000030, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_AsRSAjito_Anim_Instance' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_AsRSNpc_Anim_Instance) == 0x000040, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_AsRSNpc_Anim_Instance' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_bSuccess_1) == 0x000048, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_AsRSPlayer_Anim_Instance) == 0x000050, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_AsRSPlayer_Anim_Instance' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_bSuccess_2) == 0x000058, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_AsSkeletal_Mesh_Component) == 0x000060, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_AsSkeletal_Mesh_Component' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_bSuccess_3) == 0x000068, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_AsBPI_Player_Interface) == 0x000070, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_AsBPI_Player_Interface' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_bSuccess_4) == 0x000080, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, CallFunc_IsValid_ReturnValue_1) == 0x000081, "Member 'BP_EventMeshOption_C_Finalize::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, CallFunc_EnableRigidBody_bDummy) == 0x000082, "Member 'BP_EventMeshOption_C_Finalize::CallFunc_EnableRigidBody_bDummy' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, CallFunc_GetAnimInstance_ReturnValue_1) == 0x000088, "Member 'BP_EventMeshOption_C_Finalize::CallFunc_GetAnimInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, CallFunc_IsValid_ReturnValue_2) == 0x000090, "Member 'BP_EventMeshOption_C_Finalize::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_AsSkeletal_Mesh_Component_1) == 0x000098, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_AsSkeletal_Mesh_Component_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_bSuccess_5) == 0x0000A0, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_AsRSNpc_Anim_Instance_1) == 0x0000A8, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_AsRSNpc_Anim_Instance_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_bSuccess_6) == 0x0000B0, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_AsRSPlayer_Anim_Instance_1) == 0x0000B8, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_AsRSPlayer_Anim_Instance_1' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, K2Node_DynamicCast_bSuccess_7) == 0x0000C0, "Member 'BP_EventMeshOption_C_Finalize::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(BP_EventMeshOption_C_Finalize, CallFunc_IsValid_ReturnValue_3) == 0x0000C1, "Member 'BP_EventMeshOption_C_Finalize::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");

}

