#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PsychicObjectIntercept

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_PsychicObjectStatic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PsychicObjectIntercept.BP_PsychicObjectIntercept_C
// 0x0010 (0x05E0 - 0x05D0)
class ABP_PsychicObjectIntercept_C final : public ABP_PsychicObjectStatic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PsychicObjectIntercept_C;        // 0x05D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_PsychicObjectIntercept(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PsychicObjectIntercept_C">();
	}
	static class ABP_PsychicObjectIntercept_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PsychicObjectIntercept_C>();
	}
};
static_assert(alignof(ABP_PsychicObjectIntercept_C) == 0x000010, "Wrong alignment on ABP_PsychicObjectIntercept_C");
static_assert(sizeof(ABP_PsychicObjectIntercept_C) == 0x0005E0, "Wrong size on ABP_PsychicObjectIntercept_C");
static_assert(offsetof(ABP_PsychicObjectIntercept_C, UberGraphFrame_BP_PsychicObjectIntercept_C) == 0x0005D0, "Member 'ABP_PsychicObjectIntercept_C::UberGraphFrame_BP_PsychicObjectIntercept_C' has a wrong offset!");

}

