#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerActionStateCommonBase

#include "Basic.hpp"

#include "BattlePrototype_structs.hpp"
#include "BP_PlayerActionStateBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerActionStateCommonBase.BP_PlayerActionStateCommonBase_C
// 0x0000 (0x00E8 - 0x00E8)
class UBP_PlayerActionStateCommonBase_C : public UBP_PlayerActionStateBase_C
{
public:
	bool Transition();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PlayerActionStateCommonBase_C">();
	}
	static class UBP_PlayerActionStateCommonBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PlayerActionStateCommonBase_C>();
	}
};
static_assert(alignof(UBP_PlayerActionStateCommonBase_C) == 0x000008, "Wrong alignment on UBP_PlayerActionStateCommonBase_C");
static_assert(sizeof(UBP_PlayerActionStateCommonBase_C) == 0x0000E8, "Wrong size on UBP_PlayerActionStateCommonBase_C");

}

