#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponBase_ch0300

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_WeaponBase_ch0300.BP_WeaponBase_ch0300_C.GetAttachTransform
// 0x0060 (0x0060 - 0x0000)
struct BP_WeaponBase_ch0300_C_GetAttachTransform final
{
public:
	struct FTransform                             Transform;                                         // 0x0000(0x0030)(Parm, OutParm, IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0030(0x0030)(IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_WeaponBase_ch0300_C_GetAttachTransform) == 0x000010, "Wrong alignment on BP_WeaponBase_ch0300_C_GetAttachTransform");
static_assert(sizeof(BP_WeaponBase_ch0300_C_GetAttachTransform) == 0x000060, "Wrong size on BP_WeaponBase_ch0300_C_GetAttachTransform");
static_assert(offsetof(BP_WeaponBase_ch0300_C_GetAttachTransform, Transform) == 0x000000, "Member 'BP_WeaponBase_ch0300_C_GetAttachTransform::Transform' has a wrong offset!");
static_assert(offsetof(BP_WeaponBase_ch0300_C_GetAttachTransform, CallFunc_MakeTransform_ReturnValue) == 0x000030, "Member 'BP_WeaponBase_ch0300_C_GetAttachTransform::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");

}

