#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPBSPManagerInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPBSPManagerInterface.BPBSPManagerInterface_C
// 0x0000 (0x0028 - 0x0028)
class IBPBSPManagerInterface_C final : public IInterface
{
public:
	void RegisterAllBlocksInArea();
	void ResetBlockNearPlayer();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPBSPManagerInterface_C">();
	}
	static class IBPBSPManagerInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPBSPManagerInterface_C>();
	}
};
static_assert(alignof(IBPBSPManagerInterface_C) == 0x000008, "Wrong alignment on IBPBSPManagerInterface_C");
static_assert(sizeof(IBPBSPManagerInterface_C) == 0x000028, "Wrong size on IBPBSPManagerInterface_C");

}

