#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_OptimizeSwitchMaterial

#include "Basic.hpp"

#include "BPC_OptimizeSwitchMaterial_classes.hpp"
#include "BPC_OptimizeSwitchMaterial_parameters.hpp"


namespace SDK
{

// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.ExecuteUbergraph_BPC_OptimizeSwitchMaterial
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::ExecuteUbergraph_BPC_OptimizeSwitchMaterial(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "ExecuteUbergraph_BPC_OptimizeSwitchMaterial");

	Params::BPC_OptimizeSwitchMaterial_C_ExecuteUbergraph_BPC_OptimizeSwitchMaterial Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USkeletalMeshComponent*           SkelMeshComp                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::Initialize(class USkeletalMeshComponent* SkelMeshComp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "Initialize");

	Params::BPC_OptimizeSwitchMaterial_C_Initialize Parms{};

	Parms.SkelMeshComp = SkelMeshComp;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.InitializePlayer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARSBattlePlayer_C*                Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::InitializePlayer(class ARSBattlePlayer_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "InitializePlayer");

	Params::BPC_OptimizeSwitchMaterial_C_InitializePlayer Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.Initialize Menu Player
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_MenuPlayerBase_C*             MenuPlayer                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::Initialize_Menu_Player(class ABP_MenuPlayerBase_C* MenuPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "Initialize Menu Player");

	Params::BPC_OptimizeSwitchMaterial_C_Initialize_Menu_Player Parms{};

	Parms.MenuPlayer = MenuPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.Clear
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::Clear()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "Clear");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.SetScalarParameter
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ParameterName                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ParameterValue                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::SetScalarParameter(class FName ParameterName, float ParameterValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "SetScalarParameter");

	Params::BPC_OptimizeSwitchMaterial_C_SetScalarParameter Parms{};

	Parms.ParameterName = ParameterName;
	Parms.ParameterValue = ParameterValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.SetScalarArrayParameter
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FName>                     ParameterName                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// TArray<float>                           ParameterValue                                         (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::SetScalarArrayParameter(TArray<class FName>& ParameterName, TArray<float>& ParameterValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "SetScalarArrayParameter");

	Params::BPC_OptimizeSwitchMaterial_C_SetScalarArrayParameter Parms{};

	Parms.ParameterName = std::move(ParameterName);
	Parms.ParameterValue = std::move(ParameterValue);

	UObject::ProcessEvent(Func, &Parms);

	ParameterName = std::move(Parms.ParameterName);
	ParameterValue = std::move(Parms.ParameterValue);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.SetActivateSwitch
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Active                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBPC_OptimizeSwitchMaterial_C::SetActivateSwitch(bool Active)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "SetActivateSwitch");

	Params::BPC_OptimizeSwitchMaterial_C_SetActivateSwitch Parms{};

	Parms.Active = Active;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.CheckSwitch
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::CheckSwitch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "CheckSwitch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.RevertSwitch
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::RevertSwitch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "RevertSwitch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.IsActiveSwitch
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Param_IsActive                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBPC_OptimizeSwitchMaterial_C::IsActiveSwitch(bool* Param_IsActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "IsActiveSwitch");

	Params::BPC_OptimizeSwitchMaterial_C_IsActiveSwitch Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_IsActive != nullptr)
		*Param_IsActive = Parms.Param_IsActive;
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.EventStart
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::EventStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "EventStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.EventEnd
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::EventEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "EventEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.DestroyComponentMe
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::DestroyComponentMe()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "DestroyComponentMe");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.GetNowSettingNo
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   SettingNo                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::GetNowSettingNo(int32* SettingNo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "GetNowSettingNo");

	Params::BPC_OptimizeSwitchMaterial_C_GetNowSettingNo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SettingNo != nullptr)
		*SettingNo = Parms.SettingNo;
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.PostInitialized
// (Protected, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::PostInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "PostInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.ChangePlayerAttachment
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARSBattlePlayer_C*                Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::ChangePlayerAttachment(class ARSBattlePlayer_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "ChangePlayerAttachment");

	Params::BPC_OptimizeSwitchMaterial_C_ChangePlayerAttachment Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.ChangePlayerWeapon
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARSBattlePlayer_C*                Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::ChangePlayerWeapon(class ARSBattlePlayer_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "ChangePlayerWeapon");

	Params::BPC_OptimizeSwitchMaterial_C_ChangePlayerWeapon Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.ChangeMeshLayers
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UMeshComponent*>           MeshComps                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
// TArray<int32>                           MeshLayers                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::ChangeMeshLayers(TArray<class UMeshComponent*>& MeshComps, TArray<int32>& MeshLayers)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "ChangeMeshLayers");

	Params::BPC_OptimizeSwitchMaterial_C_ChangeMeshLayers Parms{};

	Parms.MeshComps = std::move(MeshComps);
	Parms.MeshLayers = std::move(MeshLayers);

	UObject::ProcessEvent(Func, &Parms);

	MeshComps = std::move(Parms.MeshComps);
	MeshLayers = std::move(Parms.MeshLayers);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.SwitchSetting
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::SwitchSetting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "SwitchSetting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.ChangePlayerBody
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARSBattlePlayer_C*                Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_OptimizeSwitchMaterial_C::ChangePlayerBody(class ARSBattlePlayer_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "ChangePlayerBody");

	Params::BPC_OptimizeSwitchMaterial_C_ChangePlayerBody Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.PushDisable
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::PushDisable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "PushDisable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_OptimizeSwitchMaterial.BPC_OptimizeSwitchMaterial_C.PopDisable
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_OptimizeSwitchMaterial_C::PopDisable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_OptimizeSwitchMaterial_C", "PopDisable");

	UObject::ProcessEvent(Func, nullptr);
}

}

