#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_SaveDataLoadFunction

#include "Basic.hpp"

#include "BPFL_SaveDataLoadFunction_classes.hpp"
#include "BPFL_SaveDataLoadFunction_parameters.hpp"


namespace SDK
{

// Function BPFL_SaveDataLoadFunction.BPFL_SaveDataLoadFunction_C.SaveDataLoadInitialize
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_SaveDataLoadFunction_C::SaveDataLoadInitialize(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_SaveDataLoadFunction_C", "SaveDataLoadInitialize");

	Params::BPFL_SaveDataLoadFunction_C_SaveDataLoadInitialize Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_SaveDataLoadFunction.BPFL_SaveDataLoadFunction_C.SaveDataLoadInitialize_Player
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_SaveDataLoadFunction_C::SaveDataLoadInitialize_Player(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_SaveDataLoadFunction_C", "SaveDataLoadInitialize_Player");

	Params::BPFL_SaveDataLoadFunction_C_SaveDataLoadInitialize_Player Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_SaveDataLoadFunction.BPFL_SaveDataLoadFunction_C.SaveDataLoadInitialize_Player_Position
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_SaveDataLoadFunction_C::SaveDataLoadInitialize_Player_Position(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_SaveDataLoadFunction_C", "SaveDataLoadInitialize_Player_Position");

	Params::BPFL_SaveDataLoadFunction_C_SaveDataLoadInitialize_Player_Position Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_SaveDataLoadFunction.BPFL_SaveDataLoadFunction_C.SaveDataLoadMakeEventAsset
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_SaveDataLoadFunction_C::SaveDataLoadMakeEventAsset(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_SaveDataLoadFunction_C", "SaveDataLoadMakeEventAsset");

	Params::BPFL_SaveDataLoadFunction_C_SaveDataLoadMakeEventAsset Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}

}

