#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_CableEnergy

#include "Basic.hpp"

#include "BPI_CableEnergy_classes.hpp"
#include "BPI_CableEnergy_parameters.hpp"


namespace SDK
{

// Function BPI_CableEnergy.BPI_CableEnergy_C.SetEnegyCableDissolve
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Dissolve                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ParentDissolve                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_CableEnergy_C::SetEnegyCableDissolve(float Dissolve, float ParentDissolve)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_CableEnergy_C", "SetEnegyCableDissolve");

	Params::BPI_CableEnergy_C_SetEnegyCableDissolve Parms{};

	Parms.Dissolve = Dissolve;
	Parms.ParentDissolve = ParentDissolve;

	UObject::ProcessEvent(Func, &Parms);
}

}

