#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_EnemyWeaponInterface

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BPI_EnemyWeaponInterface.BPI_EnemyWeaponInterface_C.GetLocationForHitDirection
// 0x0010 (0x0010 - 0x0000)
struct BPI_EnemyWeaponInterface_C_GetLocationForHitDirection final
{
public:
	bool                                          IsEnemyWeapon;                                     // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_112C[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                Location;                                          // 0x0004(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_EnemyWeaponInterface_C_GetLocationForHitDirection) == 0x000004, "Wrong alignment on BPI_EnemyWeaponInterface_C_GetLocationForHitDirection");
static_assert(sizeof(BPI_EnemyWeaponInterface_C_GetLocationForHitDirection) == 0x000010, "Wrong size on BPI_EnemyWeaponInterface_C_GetLocationForHitDirection");
static_assert(offsetof(BPI_EnemyWeaponInterface_C_GetLocationForHitDirection, IsEnemyWeapon) == 0x000000, "Member 'BPI_EnemyWeaponInterface_C_GetLocationForHitDirection::IsEnemyWeapon' has a wrong offset!");
static_assert(offsetof(BPI_EnemyWeaponInterface_C_GetLocationForHitDirection, Location) == 0x000004, "Member 'BPI_EnemyWeaponInterface_C_GetLocationForHitDirection::Location' has a wrong offset!");

}

