#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_MapGimmickFallFloor

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_MapGimmickFallFloor.BPI_MapGimmickFallFloor_C
// 0x0000 (0x0028 - 0x0028)
class IBPI_MapGimmickFallFloor_C final : public IInterface
{
public:
	void EV_StartFallLeftAllFromActor();
	void EV_ChangePhase(int32 PhaseNo);
	void EV_StartFallAll();
	void EV_EventLaser();
	void EV_CallStartFallBlockForce();
	void EV_EventLaserFar();
	void EV_EventLaserCenter();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_MapGimmickFallFloor_C">();
	}
	static class IBPI_MapGimmickFallFloor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_MapGimmickFallFloor_C>();
	}
};
static_assert(alignof(IBPI_MapGimmickFallFloor_C) == 0x000008, "Wrong alignment on IBPI_MapGimmickFallFloor_C");
static_assert(sizeof(IBPI_MapGimmickFallFloor_C) == 0x000028, "Wrong size on IBPI_MapGimmickFallFloor_C");

}

