#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_RSNavLinkProxy

#include "Basic.hpp"

#include "BPI_RSNavLinkProxy_classes.hpp"
#include "BPI_RSNavLinkProxy_parameters.hpp"


namespace SDK
{

// Function BPI_RSNavLinkProxy.BPI_RSNavLinkProxy_C.OnReachNavLinkPoint
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Destination                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_RSNavLinkProxy_C::OnReachNavLinkPoint(const struct FVector& Destination)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_RSNavLinkProxy_C", "OnReachNavLinkPoint");

	Params::BPI_RSNavLinkProxy_C_OnReachNavLinkPoint Parms{};

	Parms.Destination = std::move(Destination);

	UObject::ProcessEvent(Func, &Parms);
}

}

