#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FHologramRestoreMeshesAndMaterials

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct FHologramRestoreMeshesAndMaterials.FHologramRestoreMeshesAndMaterials
// 0x0018 (0x0018 - 0x0000)
struct FFHologramRestoreMeshesAndMaterials final
{
public:
	class UMeshComponent*                         RestoreMesh_2_C92AF0964D3DA0DE602BCDBA5E99D1AD;    // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInterface*>             RestoreMaterials_7_EAD783F54B64433C59E371ABE521BFFF; // 0x0008(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
};
static_assert(alignof(FFHologramRestoreMeshesAndMaterials) == 0x000008, "Wrong alignment on FFHologramRestoreMeshesAndMaterials");
static_assert(sizeof(FFHologramRestoreMeshesAndMaterials) == 0x000018, "Wrong size on FFHologramRestoreMeshesAndMaterials");
static_assert(offsetof(FFHologramRestoreMeshesAndMaterials, RestoreMesh_2_C92AF0964D3DA0DE602BCDBA5E99D1AD) == 0x000000, "Member 'FFHologramRestoreMeshesAndMaterials::RestoreMesh_2_C92AF0964D3DA0DE602BCDBA5E99D1AD' has a wrong offset!");
static_assert(offsetof(FFHologramRestoreMeshesAndMaterials, RestoreMaterials_7_EAD783F54B64433C59E371ABE521BFFF) == 0x000008, "Member 'FFHologramRestoreMeshesAndMaterials::RestoreMaterials_7_EAD783F54B64433C59E371ABE521BFFF' has a wrong offset!");

}

