#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Obj_Throw_L_Shake

#include "Basic.hpp"

#include "BattlePrototype_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Obj_Throw_L_Shake.Obj_Throw_L_Shake_C
// 0x0000 (0x0160 - 0x0160)
class UObj_Throw_L_Shake_C final : public URSCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Obj_Throw_L_Shake_C">();
	}
	static class UObj_Throw_L_Shake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UObj_Throw_L_Shake_C>();
	}
};
static_assert(alignof(UObj_Throw_L_Shake_C) == 0x000010, "Wrong alignment on UObj_Throw_L_Shake_C");
static_assert(sizeof(UObj_Throw_L_Shake_C) == 0x000160, "Wrong size on UObj_Throw_L_Shake_C");

}

