#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_SceneInfo

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct S_SceneInfo.S_SceneInfo
// 0x0010 (0x0010 - 0x0000)
struct FS_SceneInfo final
{
public:
	TArray<TSoftObjectPtr<class UObject>>         SceneSystemLevel_10_8DBBC5794AE6D8EDA72F99A02CB5C199; // 0x0000(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
};
static_assert(alignof(FS_SceneInfo) == 0x000008, "Wrong alignment on FS_SceneInfo");
static_assert(sizeof(FS_SceneInfo) == 0x000010, "Wrong size on FS_SceneInfo");
static_assert(offsetof(FS_SceneInfo, SceneSystemLevel_10_8DBBC5794AE6D8EDA72F99A02CB5C199) == 0x000000, "Member 'FS_SceneInfo::SceneSystemLevel_10_8DBBC5794AE6D8EDA72F99A02CB5C199' has a wrong offset!");

}

