#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ui_PK_weight_gauge_1

#include "Basic.hpp"

#include "WB_ui_PK_weight_gauge_1_classes.hpp"
#include "WB_ui_PK_weight_gauge_1_parameters.hpp"


namespace SDK
{

// Function WB_ui_PK_weight_gauge_1.WB_ui_PK_weight_gauge_1_C.ExecuteUbergraph_WB_ui_PK_weight_gauge_1
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_ui_PK_weight_gauge_1_C::ExecuteUbergraph_WB_ui_PK_weight_gauge_1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ui_PK_weight_gauge_1_C", "ExecuteUbergraph_WB_ui_PK_weight_gauge_1");

	Params::WB_ui_PK_weight_gauge_1_C_ExecuteUbergraph_WB_ui_PK_weight_gauge_1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_ui_PK_weight_gauge_1.WB_ui_PK_weight_gauge_1_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_ui_PK_weight_gauge_1_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ui_PK_weight_gauge_1_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_ui_PK_weight_gauge_1.WB_ui_PK_weight_gauge_1_C.UpdateState
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SubState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_ui_PK_weight_gauge_1_C::UpdateState(int32 State, int32 SubState, float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ui_PK_weight_gauge_1_C", "UpdateState");

	Params::WB_ui_PK_weight_gauge_1_C_UpdateState Parms{};

	Parms.State = State;
	Parms.SubState = SubState;
	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_ui_PK_weight_gauge_1.WB_ui_PK_weight_gauge_1_C.GetPsychicObjectWeightGaugePos
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Param_Target                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector UWB_ui_PK_weight_gauge_1_C::GetPsychicObjectWeightGaugePos(class AActor* Param_Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ui_PK_weight_gauge_1_C", "GetPsychicObjectWeightGaugePos");

	Params::WB_ui_PK_weight_gauge_1_C_GetPsychicObjectWeightGaugePos Parms{};

	Parms.Param_Target = Param_Target;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_ui_PK_weight_gauge_1.WB_ui_PK_weight_gauge_1_C.GetFontColorButton1
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWB_ui_PK_weight_gauge_1_C::GetFontColorButton1() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ui_PK_weight_gauge_1_C", "GetFontColorButton1");

	Params::WB_ui_PK_weight_gauge_1_C_GetFontColorButton1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_ui_PK_weight_gauge_1.WB_ui_PK_weight_gauge_1_C.GetFontColorButton2
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWB_ui_PK_weight_gauge_1_C::GetFontColorButton2() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ui_PK_weight_gauge_1_C", "GetFontColorButton2");

	Params::WB_ui_PK_weight_gauge_1_C_GetFontColorButton2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

