#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ui_Sas_page_01

#include "Basic.hpp"

#include "BattlePrototype_structs.hpp"
#include "InputCore_structs.hpp"


namespace SDK::Params
{

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.ExecuteUbergraph_WB_ui_Sas_page_01
// 0x0088 (0x0088 - 0x0000)
struct WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47BD[0x2];                                     // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_3;            // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47BE[0x2];                                     // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_2;             // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_3;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_4;            // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_5;            // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47BF[0x2];                                     // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_4;             // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_6;            // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C0[0x3];                                     // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_5;             // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_6;             // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_State;                                // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_SubState;                             // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_7;            // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C1[0x3];                                     // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_7;             // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_8;            // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C2[0x2];                                     // 0x0046(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_8;             // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_9;            // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C3[0x3];                                     // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_9;             // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_10;           // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C4[0x3];                                     // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_10;            // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C5[0x4];                                     // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AHUDMainGame_C*                         CallFunc_GetHUDMainGame_HUDMainGame;               // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_isChangedIconDeviceType_ReturnValue;      // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_11;           // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_12;           // 0x006A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C6[0x1];                                     // 0x006B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_11;            // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_12;            // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_13;           // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C7[0x3];                                     // 0x0075(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_13;            // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_14;           // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C8[0x3];                                     // 0x007D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_14;            // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01) == 0x000008, "Wrong alignment on WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01");
static_assert(sizeof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01) == 0x000088, "Wrong size on WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, EntryPoint) == 0x000000, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::EntryPoint' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue) == 0x000004, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000005, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000008, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x00000C, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_2) == 0x000010, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_3) == 0x000011, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_2) == 0x000014, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_3) == 0x000018, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_4) == 0x00001C, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_5) == 0x00001D, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_4) == 0x000020, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_6) == 0x000024, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_5) == 0x000028, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_6) == 0x00002C, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, K2Node_Event_State) == 0x000030, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::K2Node_Event_State' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, K2Node_Event_SubState) == 0x000034, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::K2Node_Event_SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, K2Node_Event_DeltaSeconds) == 0x000038, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_7) == 0x00003C, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_7) == 0x000040, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, K2Node_SwitchInteger_CmpSuccess) == 0x000044, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_8) == 0x000045, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_8) == 0x000048, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_9) == 0x00004C, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_9) == 0x000050, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_10) == 0x000054, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_10) == 0x000058, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_GetHUDMainGame_HUDMainGame) == 0x000060, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_GetHUDMainGame_HUDMainGame' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_isChangedIconDeviceType_ReturnValue) == 0x000068, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_isChangedIconDeviceType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_11) == 0x000069, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_12) == 0x00006A, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_11) == 0x00006C, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_12) == 0x000070, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_13) == 0x000074, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_13) == 0x000078, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_MakeLiteralByte_ReturnValue_14) == 0x00007C, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_MakeLiteralByte_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01, CallFunc_Conv_ByteToInt_ReturnValue_14) == 0x000080, "Member 'WB_ui_Sas_page_01_C_ExecuteUbergraph_WB_ui_Sas_page_01::CallFunc_Conv_ByteToInt_ReturnValue_14' has a wrong offset!");

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.UpdateState
// 0x000C (0x000C - 0x0000)
struct WB_ui_Sas_page_01_C_UpdateState final
{
public:
	int32                                         State;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SubState;                                          // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DeltaSeconds;                                      // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Sas_page_01_C_UpdateState) == 0x000004, "Wrong alignment on WB_ui_Sas_page_01_C_UpdateState");
static_assert(sizeof(WB_ui_Sas_page_01_C_UpdateState) == 0x00000C, "Wrong size on WB_ui_Sas_page_01_C_UpdateState");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateState, State) == 0x000000, "Member 'WB_ui_Sas_page_01_C_UpdateState::State' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateState, SubState) == 0x000004, "Member 'WB_ui_Sas_page_01_C_UpdateState::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateState, DeltaSeconds) == 0x000008, "Member 'WB_ui_Sas_page_01_C_UpdateState::DeltaSeconds' has a wrong offset!");

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.StateNone
// 0x000C (0x000C - 0x0000)
struct WB_ui_Sas_page_01_C_StateNone final
{
public:
	int32                                         SubState;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSasControllChange_ReturnValue;         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C9[0x1];                                     // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Sas_page_01_C_StateNone) == 0x000004, "Wrong alignment on WB_ui_Sas_page_01_C_StateNone");
static_assert(sizeof(WB_ui_Sas_page_01_C_StateNone) == 0x00000C, "Wrong size on WB_ui_Sas_page_01_C_StateNone");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateNone, SubState) == 0x000000, "Member 'WB_ui_Sas_page_01_C_StateNone::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateNone, CallFunc_GetSasControllChange_ReturnValue) == 0x000004, "Member 'WB_ui_Sas_page_01_C_StateNone::CallFunc_GetSasControllChange_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateNone, K2Node_SwitchInteger_CmpSuccess) == 0x000005, "Member 'WB_ui_Sas_page_01_C_StateNone::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateNone, CallFunc_MakeLiteralByte_ReturnValue) == 0x000006, "Member 'WB_ui_Sas_page_01_C_StateNone::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateNone, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000008, "Member 'WB_ui_Sas_page_01_C_StateNone::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.StateLoopL
// 0x0040 (0x0040 - 0x0000)
struct WB_ui_Sas_page_01_C_StateLoopL final
{
public:
	int32                                         SubState;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47CA[0x2];                                     // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_3;            // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47CB[0x1];                                     // 0x0013(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_2;             // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_3;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_4;            // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47CC[0x2];                                     // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_4;             // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0026(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_5;            // 0x0027(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay_1;        // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47CD[0x3];                                     // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_5;             // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_6;            // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay_2;        // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47CE[0x2];                                     // 0x0032(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_6;             // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_7;            // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47CF[0x3];                                     // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_7;             // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Sas_page_01_C_StateLoopL) == 0x000004, "Wrong alignment on WB_ui_Sas_page_01_C_StateLoopL");
static_assert(sizeof(WB_ui_Sas_page_01_C_StateLoopL) == 0x000040, "Wrong size on WB_ui_Sas_page_01_C_StateLoopL");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, SubState) == 0x000000, "Member 'WB_ui_Sas_page_01_C_StateLoopL::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_MakeLiteralByte_ReturnValue) == 0x000004, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000005, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000008, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x00000C, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_IsPlayUICurrentAnimation_isPlay) == 0x000010, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_IsPlayUICurrentAnimation_isPlay' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_MakeLiteralByte_ReturnValue_2) == 0x000011, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_MakeLiteralByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_MakeLiteralByte_ReturnValue_3) == 0x000012, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_MakeLiteralByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_Conv_ByteToInt_ReturnValue_2) == 0x000014, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_Conv_ByteToInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_Conv_ByteToInt_ReturnValue_3) == 0x000018, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_Conv_ByteToInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_MakeLiteralByte_ReturnValue_4) == 0x00001C, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_MakeLiteralByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_Less_IntInt_ReturnValue) == 0x00001D, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_Conv_ByteToInt_ReturnValue_4) == 0x000020, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_Conv_ByteToInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000024, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, K2Node_SwitchInteger_CmpSuccess) == 0x000025, "Member 'WB_ui_Sas_page_01_C_StateLoopL::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_BooleanAND_ReturnValue) == 0x000026, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_MakeLiteralByte_ReturnValue_5) == 0x000027, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_MakeLiteralByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_IsPlayUICurrentAnimation_isPlay_1) == 0x000028, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_IsPlayUICurrentAnimation_isPlay_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_Conv_ByteToInt_ReturnValue_5) == 0x00002C, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_Conv_ByteToInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_MakeLiteralByte_ReturnValue_6) == 0x000030, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_MakeLiteralByte_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_IsPlayUICurrentAnimation_isPlay_2) == 0x000031, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_IsPlayUICurrentAnimation_isPlay_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_Conv_ByteToInt_ReturnValue_6) == 0x000034, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_Conv_ByteToInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_MakeLiteralByte_ReturnValue_7) == 0x000038, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_MakeLiteralByte_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopL, CallFunc_Conv_ByteToInt_ReturnValue_7) == 0x00003C, "Member 'WB_ui_Sas_page_01_C_StateLoopL::CallFunc_Conv_ByteToInt_ReturnValue_7' has a wrong offset!");

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.StateLoopR
// 0x0038 (0x0038 - 0x0000)
struct WB_ui_Sas_page_01_C_StateLoopR final
{
public:
	int32                                         SubState;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47D0[0x2];                                     // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_3;            // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47D1[0x1];                                     // 0x0013(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_2;             // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_3;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay_1;        // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_4;            // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_5;            // 0x001E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47D2[0x1];                                     // 0x001F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_4;             // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_5;             // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_6;            // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x002B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_6;             // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay_2;        // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_7;            // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47D3[0x1];                                     // 0x0033(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_7;             // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Sas_page_01_C_StateLoopR) == 0x000004, "Wrong alignment on WB_ui_Sas_page_01_C_StateLoopR");
static_assert(sizeof(WB_ui_Sas_page_01_C_StateLoopR) == 0x000038, "Wrong size on WB_ui_Sas_page_01_C_StateLoopR");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, SubState) == 0x000000, "Member 'WB_ui_Sas_page_01_C_StateLoopR::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_MakeLiteralByte_ReturnValue) == 0x000004, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000005, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000008, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x00000C, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_IsPlayUICurrentAnimation_isPlay) == 0x000010, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_IsPlayUICurrentAnimation_isPlay' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_MakeLiteralByte_ReturnValue_2) == 0x000011, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_MakeLiteralByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_MakeLiteralByte_ReturnValue_3) == 0x000012, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_MakeLiteralByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_Conv_ByteToInt_ReturnValue_2) == 0x000014, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_Conv_ByteToInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_Conv_ByteToInt_ReturnValue_3) == 0x000018, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_Conv_ByteToInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_IsPlayUICurrentAnimation_isPlay_1) == 0x00001C, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_IsPlayUICurrentAnimation_isPlay_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_MakeLiteralByte_ReturnValue_4) == 0x00001D, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_MakeLiteralByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_MakeLiteralByte_ReturnValue_5) == 0x00001E, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_MakeLiteralByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_Conv_ByteToInt_ReturnValue_4) == 0x000020, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_Conv_ByteToInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_Conv_ByteToInt_ReturnValue_5) == 0x000024, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_Conv_ByteToInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_Less_IntInt_ReturnValue) == 0x000028, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000029, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_MakeLiteralByte_ReturnValue_6) == 0x00002A, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_MakeLiteralByte_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_BooleanAND_ReturnValue) == 0x00002B, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_Conv_ByteToInt_ReturnValue_6) == 0x00002C, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_Conv_ByteToInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, K2Node_SwitchInteger_CmpSuccess) == 0x000030, "Member 'WB_ui_Sas_page_01_C_StateLoopR::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_IsPlayUICurrentAnimation_isPlay_2) == 0x000031, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_IsPlayUICurrentAnimation_isPlay_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_MakeLiteralByte_ReturnValue_7) == 0x000032, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_MakeLiteralByte_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateLoopR, CallFunc_Conv_ByteToInt_ReturnValue_7) == 0x000034, "Member 'WB_ui_Sas_page_01_C_StateLoopR::CallFunc_Conv_ByteToInt_ReturnValue_7' has a wrong offset!");

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.SetPage
// 0x0004 (0x0004 - 0x0000)
struct WB_ui_Sas_page_01_C_SetPage final
{
public:
	int32                                         Param_Page;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Sas_page_01_C_SetPage) == 0x000004, "Wrong alignment on WB_ui_Sas_page_01_C_SetPage");
static_assert(sizeof(WB_ui_Sas_page_01_C_SetPage) == 0x000004, "Wrong size on WB_ui_Sas_page_01_C_SetPage");
static_assert(offsetof(WB_ui_Sas_page_01_C_SetPage, Param_Page) == 0x000000, "Member 'WB_ui_Sas_page_01_C_SetPage::Param_Page' has a wrong offset!");

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.UpdateButton
// 0x0080 (0x0080 - 0x0000)
struct WB_ui_Sas_page_01_C_UpdateButton final
{
public:
	TArray<class FString>                         _KeyList;                                          // 0x0000(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<EChangeableControllerKey>              _ButtonList;                                       // 0x0010(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	int32                                         _index;                                            // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         _DrawType;                                         // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<EChangeableControllerKey>              K2Node_MakeArray_Array;                            // 0x0028(0x0010)(ReferenceParm, HasGetValueTypeHash)
	class UUserParamManager*                      CallFunc_GetUserParamManager_UserParamManager;     // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UOptionParam*                           CallFunc_GetOptionParam_ReturnValue;               // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ERSGamepadInputName                           CallFunc_GetControllerParamValue_ReturnValue;      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47D4[0x6];                                     // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         K2Node_MakeArray_Array_1;                          // 0x0050(0x0010)(ReferenceParm, HasGetValueTypeHash)
	class AHUDMainGame_C*                         CallFunc_GetHUDMainGame_HUDMainGame;               // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetPlatformName_ReturnValue;              // 0x0068(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	EInputDeviceType                              CallFunc_getIconDeviceType_ReturnValue;            // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue_1;          // 0x007B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WB_ui_Sas_page_01_C_UpdateButton) == 0x000008, "Wrong alignment on WB_ui_Sas_page_01_C_UpdateButton");
static_assert(sizeof(WB_ui_Sas_page_01_C_UpdateButton) == 0x000080, "Wrong size on WB_ui_Sas_page_01_C_UpdateButton");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, _KeyList) == 0x000000, "Member 'WB_ui_Sas_page_01_C_UpdateButton::_KeyList' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, _ButtonList) == 0x000010, "Member 'WB_ui_Sas_page_01_C_UpdateButton::_ButtonList' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, _index) == 0x000020, "Member 'WB_ui_Sas_page_01_C_UpdateButton::_index' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, _DrawType) == 0x000024, "Member 'WB_ui_Sas_page_01_C_UpdateButton::_DrawType' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, K2Node_MakeArray_Array) == 0x000028, "Member 'WB_ui_Sas_page_01_C_UpdateButton::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, CallFunc_GetUserParamManager_UserParamManager) == 0x000038, "Member 'WB_ui_Sas_page_01_C_UpdateButton::CallFunc_GetUserParamManager_UserParamManager' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, CallFunc_GetOptionParam_ReturnValue) == 0x000040, "Member 'WB_ui_Sas_page_01_C_UpdateButton::CallFunc_GetOptionParam_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, CallFunc_GetControllerParamValue_ReturnValue) == 0x000048, "Member 'WB_ui_Sas_page_01_C_UpdateButton::CallFunc_GetControllerParamValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, K2Node_SwitchInteger_CmpSuccess) == 0x000049, "Member 'WB_ui_Sas_page_01_C_UpdateButton::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, K2Node_MakeArray_Array_1) == 0x000050, "Member 'WB_ui_Sas_page_01_C_UpdateButton::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, CallFunc_GetHUDMainGame_HUDMainGame) == 0x000060, "Member 'WB_ui_Sas_page_01_C_UpdateButton::CallFunc_GetHUDMainGame_HUDMainGame' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, CallFunc_GetPlatformName_ReturnValue) == 0x000068, "Member 'WB_ui_Sas_page_01_C_UpdateButton::CallFunc_GetPlatformName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, CallFunc_getIconDeviceType_ReturnValue) == 0x000078, "Member 'WB_ui_Sas_page_01_C_UpdateButton::CallFunc_getIconDeviceType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x000079, "Member 'WB_ui_Sas_page_01_C_UpdateButton::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, K2Node_SwitchEnum_CmpSuccess) == 0x00007A, "Member 'WB_ui_Sas_page_01_C_UpdateButton::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, CallFunc_EqualEqual_StrStr_ReturnValue_1) == 0x00007B, "Member 'WB_ui_Sas_page_01_C_UpdateButton::CallFunc_EqualEqual_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_UpdateButton, CallFunc_BooleanOR_ReturnValue) == 0x00007C, "Member 'WB_ui_Sas_page_01_C_UpdateButton::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.StateOpen
// 0x001C (0x001C - 0x0000)
struct WB_ui_Sas_page_01_C_StateOpen final
{
public:
	int32                                         SubState;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47D5[0x2];                                     // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay;          // 0x000E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47D6[0x1];                                     // 0x000F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47D7[0x3];                                     // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_2;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Sas_page_01_C_StateOpen) == 0x000004, "Wrong alignment on WB_ui_Sas_page_01_C_StateOpen");
static_assert(sizeof(WB_ui_Sas_page_01_C_StateOpen) == 0x00001C, "Wrong size on WB_ui_Sas_page_01_C_StateOpen");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, SubState) == 0x000000, "Member 'WB_ui_Sas_page_01_C_StateOpen::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, CallFunc_MakeLiteralByte_ReturnValue) == 0x000004, "Member 'WB_ui_Sas_page_01_C_StateOpen::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, K2Node_SwitchInteger_CmpSuccess) == 0x000005, "Member 'WB_ui_Sas_page_01_C_StateOpen::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000008, "Member 'WB_ui_Sas_page_01_C_StateOpen::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x00000C, "Member 'WB_ui_Sas_page_01_C_StateOpen::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x00000D, "Member 'WB_ui_Sas_page_01_C_StateOpen::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, CallFunc_IsPlayUICurrentAnimation_isPlay) == 0x00000E, "Member 'WB_ui_Sas_page_01_C_StateOpen::CallFunc_IsPlayUICurrentAnimation_isPlay' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x000010, "Member 'WB_ui_Sas_page_01_C_StateOpen::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, CallFunc_MakeLiteralByte_ReturnValue_2) == 0x000014, "Member 'WB_ui_Sas_page_01_C_StateOpen::CallFunc_MakeLiteralByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateOpen, CallFunc_Conv_ByteToInt_ReturnValue_2) == 0x000018, "Member 'WB_ui_Sas_page_01_C_StateOpen::CallFunc_Conv_ByteToInt_ReturnValue_2' has a wrong offset!");

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.StateClose
// 0x0014 (0x0014 - 0x0000)
struct WB_ui_Sas_page_01_C_StateClose final
{
public:
	int32                                         SubState;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47D8[0x1];                                     // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WB_ui_Sas_page_01_C_StateClose) == 0x000004, "Wrong alignment on WB_ui_Sas_page_01_C_StateClose");
static_assert(sizeof(WB_ui_Sas_page_01_C_StateClose) == 0x000014, "Wrong size on WB_ui_Sas_page_01_C_StateClose");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateClose, SubState) == 0x000000, "Member 'WB_ui_Sas_page_01_C_StateClose::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateClose, CallFunc_MakeLiteralByte_ReturnValue) == 0x000004, "Member 'WB_ui_Sas_page_01_C_StateClose::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateClose, K2Node_SwitchInteger_CmpSuccess) == 0x000005, "Member 'WB_ui_Sas_page_01_C_StateClose::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateClose, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000006, "Member 'WB_ui_Sas_page_01_C_StateClose::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateClose, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000008, "Member 'WB_ui_Sas_page_01_C_StateClose::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateClose, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x00000C, "Member 'WB_ui_Sas_page_01_C_StateClose::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_StateClose, CallFunc_IsPlayUICurrentAnimation_isPlay) == 0x000010, "Member 'WB_ui_Sas_page_01_C_StateClose::CallFunc_IsPlayUICurrentAnimation_isPlay' has a wrong offset!");

// Function WB_ui_Sas_page_01.WB_ui_Sas_page_01_C.SetReady
// 0x0003 (0x0003 - 0x0000)
struct WB_ui_Sas_page_01_C_SetReady final
{
public:
	bool                                          IsReadyL;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsReadyR;                                          // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WB_ui_Sas_page_01_C_SetReady) == 0x000001, "Wrong alignment on WB_ui_Sas_page_01_C_SetReady");
static_assert(sizeof(WB_ui_Sas_page_01_C_SetReady) == 0x000003, "Wrong size on WB_ui_Sas_page_01_C_SetReady");
static_assert(offsetof(WB_ui_Sas_page_01_C_SetReady, IsReadyL) == 0x000000, "Member 'WB_ui_Sas_page_01_C_SetReady::IsReadyL' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_SetReady, IsReadyR) == 0x000001, "Member 'WB_ui_Sas_page_01_C_SetReady::IsReadyR' has a wrong offset!");
static_assert(offsetof(WB_ui_Sas_page_01_C_SetReady, CallFunc_BooleanOR_ReturnValue) == 0x000002, "Member 'WB_ui_Sas_page_01_C_SetReady::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

}

