#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ui_Present_List_Parts_1

#include "Basic.hpp"

#include "BattlePrototype_structs.hpp"


namespace SDK::Params
{

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.ExecuteUbergraph_WB_ui_Present_List_Parts_1
// 0x0044 (0x0044 - 0x0000)
struct WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57EB[0x2];                                     // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_3;            // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57EC[0x2];                                     // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_2;             // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_3;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_4;            // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57ED[0x3];                                     // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_4;             // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_5;            // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_6;            // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57EE[0x2];                                     // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_5;             // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_6;             // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_State;                                // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_SubState;                             // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_7;            // 0x003D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57EF[0x2];                                     // 0x003E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_7;             // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1) == 0x000004, "Wrong alignment on WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1) == 0x000044, "Wrong size on WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, EntryPoint) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::EntryPoint' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_MakeLiteralByte_ReturnValue) == 0x000004, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000005, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000008, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x00000C, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_MakeLiteralByte_ReturnValue_2) == 0x000010, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_MakeLiteralByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_MakeLiteralByte_ReturnValue_3) == 0x000011, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_MakeLiteralByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_Conv_ByteToInt_ReturnValue_2) == 0x000014, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_Conv_ByteToInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_Conv_ByteToInt_ReturnValue_3) == 0x000018, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_Conv_ByteToInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_MakeLiteralByte_ReturnValue_4) == 0x00001C, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_MakeLiteralByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_Conv_ByteToInt_ReturnValue_4) == 0x000020, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_Conv_ByteToInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_MakeLiteralByte_ReturnValue_5) == 0x000024, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_MakeLiteralByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_MakeLiteralByte_ReturnValue_6) == 0x000025, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_MakeLiteralByte_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_Conv_ByteToInt_ReturnValue_5) == 0x000028, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_Conv_ByteToInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_Conv_ByteToInt_ReturnValue_6) == 0x00002C, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_Conv_ByteToInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, K2Node_Event_State) == 0x000030, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::K2Node_Event_State' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, K2Node_Event_SubState) == 0x000034, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::K2Node_Event_SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, K2Node_Event_DeltaSeconds) == 0x000038, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, K2Node_SwitchInteger_CmpSuccess) == 0x00003C, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_MakeLiteralByte_ReturnValue_7) == 0x00003D, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_MakeLiteralByte_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1, CallFunc_Conv_ByteToInt_ReturnValue_7) == 0x000040, "Member 'WB_ui_Present_List_Parts_1_C_ExecuteUbergraph_WB_ui_Present_List_Parts_1::CallFunc_Conv_ByteToInt_ReturnValue_7' has a wrong offset!");

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.UpdateState
// 0x000C (0x000C - 0x0000)
struct WB_ui_Present_List_Parts_1_C_UpdateState final
{
public:
	int32                                         State;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SubState;                                          // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DeltaSeconds;                                      // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_UpdateState) == 0x000004, "Wrong alignment on WB_ui_Present_List_Parts_1_C_UpdateState");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_UpdateState) == 0x00000C, "Wrong size on WB_ui_Present_List_Parts_1_C_UpdateState");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_UpdateState, State) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_UpdateState::State' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_UpdateState, SubState) == 0x000004, "Member 'WB_ui_Present_List_Parts_1_C_UpdateState::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_UpdateState, DeltaSeconds) == 0x000008, "Member 'WB_ui_Present_List_Parts_1_C_UpdateState::DeltaSeconds' has a wrong offset!");

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.StateNone
// 0x0010 (0x0010 - 0x0000)
struct WB_ui_Present_List_Parts_1_C_StateNone final
{
public:
	int32                                         SubState;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57F0[0x1];                                     // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_StateNone) == 0x000004, "Wrong alignment on WB_ui_Present_List_Parts_1_C_StateNone");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_StateNone) == 0x000010, "Wrong size on WB_ui_Present_List_Parts_1_C_StateNone");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateNone, SubState) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_StateNone::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateNone, CallFunc_MakeLiteralByte_ReturnValue) == 0x000004, "Member 'WB_ui_Present_List_Parts_1_C_StateNone::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateNone, K2Node_SwitchInteger_CmpSuccess) == 0x000005, "Member 'WB_ui_Present_List_Parts_1_C_StateNone::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateNone, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000006, "Member 'WB_ui_Present_List_Parts_1_C_StateNone::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateNone, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000008, "Member 'WB_ui_Present_List_Parts_1_C_StateNone::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateNone, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x00000C, "Member 'WB_ui_Present_List_Parts_1_C_StateNone::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.StateLoop
// 0x0028 (0x0028 - 0x0000)
struct WB_ui_Present_List_Parts_1_C_StateLoop final
{
public:
	int32                                         SubState;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         _WorkSubState;                                     // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay;          // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_57F1[0x1];                                     // 0x000B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57F2[0x2];                                     // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_2;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_3;            // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57F3[0x3];                                     // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_3;             // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess_1;                 // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_StateLoop) == 0x000004, "Wrong alignment on WB_ui_Present_List_Parts_1_C_StateLoop");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_StateLoop) == 0x000028, "Wrong size on WB_ui_Present_List_Parts_1_C_StateLoop");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, SubState) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, _WorkSubState) == 0x000004, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::_WorkSubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, K2Node_SwitchInteger_CmpSuccess) == 0x000008, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, CallFunc_MakeLiteralByte_ReturnValue) == 0x000009, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, CallFunc_IsPlayUICurrentAnimation_isPlay) == 0x00000A, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::CallFunc_IsPlayUICurrentAnimation_isPlay' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, CallFunc_Conv_ByteToInt_ReturnValue) == 0x00000C, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000010, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, CallFunc_MakeLiteralByte_ReturnValue_2) == 0x000011, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::CallFunc_MakeLiteralByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x000014, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, CallFunc_Conv_ByteToInt_ReturnValue_2) == 0x000018, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::CallFunc_Conv_ByteToInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, CallFunc_MakeLiteralByte_ReturnValue_3) == 0x00001C, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::CallFunc_MakeLiteralByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, CallFunc_Conv_ByteToInt_ReturnValue_3) == 0x000020, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::CallFunc_Conv_ByteToInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoop, K2Node_SwitchInteger_CmpSuccess_1) == 0x000024, "Member 'WB_ui_Present_List_Parts_1_C_StateLoop::K2Node_SwitchInteger_CmpSuccess_1' has a wrong offset!");

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.StateLoopSelect
// 0x0028 (0x0028 - 0x0000)
struct WB_ui_Present_List_Parts_1_C_StateLoopSelect final
{
public:
	int32                                         SubState;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57F4[0x1];                                     // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlayUICurrentAnimation_isPlay_1;        // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57F5[0x1];                                     // 0x0013(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_2;             // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_3;            // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57F6[0x3];                                     // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_3;             // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_4;            // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57F7[0x3];                                     // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_4;             // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_StateLoopSelect) == 0x000004, "Wrong alignment on WB_ui_Present_List_Parts_1_C_StateLoopSelect");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_StateLoopSelect) == 0x000028, "Wrong size on WB_ui_Present_List_Parts_1_C_StateLoopSelect");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, SubState) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::SubState' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_MakeLiteralByte_ReturnValue) == 0x000004, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, K2Node_SwitchInteger_CmpSuccess) == 0x000005, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000006, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000008, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x00000C, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_IsPlayUICurrentAnimation_isPlay) == 0x000010, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_IsPlayUICurrentAnimation_isPlay' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_IsPlayUICurrentAnimation_isPlay_1) == 0x000011, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_IsPlayUICurrentAnimation_isPlay_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_MakeLiteralByte_ReturnValue_2) == 0x000012, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_MakeLiteralByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_Conv_ByteToInt_ReturnValue_2) == 0x000014, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_Conv_ByteToInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_MakeLiteralByte_ReturnValue_3) == 0x000018, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_MakeLiteralByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_Conv_ByteToInt_ReturnValue_3) == 0x00001C, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_Conv_ByteToInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_MakeLiteralByte_ReturnValue_4) == 0x000020, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_MakeLiteralByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_StateLoopSelect, CallFunc_Conv_ByteToInt_ReturnValue_4) == 0x000024, "Member 'WB_ui_Present_List_Parts_1_C_StateLoopSelect::CallFunc_Conv_ByteToInt_ReturnValue_4' has a wrong offset!");

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.SetSelect
// 0x0001 (0x0001 - 0x0000)
struct WB_ui_Present_List_Parts_1_C_SetSelect final
{
public:
	bool                                          Param_IsSelect;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_SetSelect) == 0x000001, "Wrong alignment on WB_ui_Present_List_Parts_1_C_SetSelect");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_SetSelect) == 0x000001, "Wrong size on WB_ui_Present_List_Parts_1_C_SetSelect");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetSelect, Param_IsSelect) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_SetSelect::Param_IsSelect' has a wrong offset!");

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.SetItem
// 0x00F8 (0x00F8 - 0x0000)
struct WB_ui_Present_List_Parts_1_C_SetItem final
{
public:
	class FName                                   Param_ItemId;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Param_IsNew;                                       // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_57F8[0x7];                                     // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDatabaseManager*                       CallFunc_GetDataBaseManager_Manager;               // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UItemData*                              CallFunc_GetItemData_ReturnValue;                  // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FItemDataCell                          CallFunc_GetData_ItemData;                         // 0x0020(0x0080)()
	bool                                          CallFunc_GetData_ReturnValue;                      // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_57F9[0x7];                                     // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x00A8(0x0018)()
	class FString                                 CallFunc_GetText_ReturnValue;                      // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00D0(0x0018)()
	class UUserParamManager*                      CallFunc_GetUserParamManager_UserParamManager;     // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetItemNum_ReturnValue;                   // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_SetItem) == 0x000008, "Wrong alignment on WB_ui_Present_List_Parts_1_C_SetItem");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_SetItem) == 0x0000F8, "Wrong size on WB_ui_Present_List_Parts_1_C_SetItem");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, Param_ItemId) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::Param_ItemId' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, Param_IsNew) == 0x000008, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::Param_IsNew' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, CallFunc_GetDataBaseManager_Manager) == 0x000010, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::CallFunc_GetDataBaseManager_Manager' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, CallFunc_GetItemData_ReturnValue) == 0x000018, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::CallFunc_GetItemData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, CallFunc_GetData_ItemData) == 0x000020, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::CallFunc_GetData_ItemData' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, CallFunc_GetData_ReturnValue) == 0x0000A0, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::CallFunc_GetData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, CallFunc_Conv_IntToText_ReturnValue) == 0x0000A8, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, CallFunc_GetText_ReturnValue) == 0x0000C0, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, CallFunc_Conv_StringToText_ReturnValue) == 0x0000D0, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, CallFunc_GetUserParamManager_UserParamManager) == 0x0000E8, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::CallFunc_GetUserParamManager_UserParamManager' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetItem, CallFunc_GetItemNum_ReturnValue) == 0x0000F0, "Member 'WB_ui_Present_List_Parts_1_C_SetItem::CallFunc_GetItemNum_ReturnValue' has a wrong offset!");

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.SetNewFlag
// 0x0001 (0x0001 - 0x0000)
struct WB_ui_Present_List_Parts_1_C_SetNewFlag final
{
public:
	bool                                          Param_IsNew;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_SetNewFlag) == 0x000001, "Wrong alignment on WB_ui_Present_List_Parts_1_C_SetNewFlag");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_SetNewFlag) == 0x000001, "Wrong size on WB_ui_Present_List_Parts_1_C_SetNewFlag");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetNewFlag, Param_IsNew) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_SetNewFlag::Param_IsNew' has a wrong offset!");

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.SetMouseSelectFocus
// 0x000C (0x000C - 0x0000)
struct WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus final
{
public:
	bool                                          Param_IsSelect;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57FA[0x1];                                     // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus) == 0x000004, "Wrong alignment on WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus) == 0x00000C, "Wrong size on WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus, Param_IsSelect) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus::Param_IsSelect' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus, CallFunc_MakeLiteralByte_ReturnValue) == 0x000001, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000002, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000004, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x000008, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectFocus::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");

// Function WB_ui_Present_List_Parts_1.WB_ui_Present_List_Parts_1_C.SetMouseSelectUnFocus
// 0x000C (0x000C - 0x0000)
struct WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus final
{
public:
	bool                                          Param_IsSelect;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57FB[0x1];                                     // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus) == 0x000004, "Wrong alignment on WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus");
static_assert(sizeof(WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus) == 0x00000C, "Wrong size on WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus, Param_IsSelect) == 0x000000, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus::Param_IsSelect' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus, CallFunc_MakeLiteralByte_ReturnValue) == 0x000001, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000002, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000004, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x000008, "Member 'WB_ui_Present_List_Parts_1_C_SetMouseSelectUnFocus::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");

}

